- id: leibal_arch
  name: Leibal / Architecture
  list_url: https://leibal.com/category/architecture/
  paging: wp_page

- id: leibal_int
  name: Leibal / Interiors
  list_url: https://leibal.com/category/interiors/
  paging: wp_page

- id: archdaily_projects
  name: ArchDaily / Residential Architecture
  list_url: https://www.archdaily.com/category/residential-architecture
  paging: archdaily_category_page

- id: archdaily_landscape
  name: ArchDaily / Landscape Architecture
  list_url: https://www.archdaily.com/category/landscape-architecture
  paging: archdaily_category_page

- id: dezeen_arch
  name: Dezeen / Architecture
  list_url: https://www.dezeen.com/feed/?post_type=post&taxonomy=category&term=architecture
  paging: rss

- id: dezeen_int
  name: Dezeen / Interiors
  list_url: https://www.dezeen.com/feed/?post_type=post&taxonomy=category&term=interiors
  paging: rss

- id: landezine_play
  name: Landezine / Playground
  list_url: https://landezine.com/landscapes/landscape-architecture/realized-projects/playground/
  paging: wp_page


- id: wla
  name: World Landscape Architect
  list_url: https://worldlandscapearchitect.com/
  paging: wp_page
