- id: leibal_arch
  name: Leibal / Architecture
  list_url: https://leibal.com/category/architecture/
  paging: wp_page

- id: leibal_int
  name: Leibal / Interiors
  list_url: https://leibal.com/category/interiors/
  paging: wp_page

- id: archdaily_projects
  name: ArchDaily / Projects
  list_url: https://www.archdaily.com/search/projects?ad_source=jv-header&ad_name=main-menu&is_allowed_bot=true
  paging: archdaily_search_page

- id: archdaily_landscape
  name: ArchDaily / Landscape Architecture
  list_url: https://www.archdaily.com/search/projects/categories/landscape-architecture?is_allowed_bot=true
  paging: archdaily_search_page

- id: dezeen_arch
  name: Dezeen / Architecture
  list_url: https://www.dezeen.com/architecture/
  paging: dezeen_page

- id: dezeen_int
  name: Dezeen / Interiors
  list_url: https://www.dezeen.com/interiors/
  paging: dezeen_page

- id: landezine_play
  name: Landezine / Playground
  list_url: https://landezine.com/landscapes/landscape-architecture/realized-projects/playground/
  paging: wp_page

- id: wla
  name: World Landscape Architect
  list_url: https://worldlandscapearchitect.com/?v=5f02f0889301
  paging: wp_page
